# Generated by Django 3.2.3 on 2021-05-24 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Название поста для страницы "О нас"', max_length=250, verbose_name='Название')),
                ('image', models.ImageField(upload_to='about/', verbose_name='Изображение')),
                ('content', models.TextField(verbose_name='Контент')),
            ],
        ),
    ]
